
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # this labels is for replicaset
  labels:
    project: roboshop
    tier: frontend
    component: nginx
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      # these labels is for replicaset to select the pods
      project: roboshop
      tier: frontend
      component: nginx
      environment: dev
  template:
    metadata:
    # these for pod defination
      labels:
        project: roboshop
        tier: frontend
        component: nginx
        environment: dev
    spec:
      containers:
      - name: frontend
        image: krishna88s/frontend:1.1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 4
          periodSeconds: 10
          initialDelaySeconds: 15   
        livenessProbe: 
          httpGet:
            path: /
            port: 80
          failureThreshold: 4
          periodSeconds: 10   
      
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  selector:
      project: roboshop
      tier: frontend
      component: nginx
      environment: dev

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

