apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev

data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # this labels is for replicaset
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      # these labels is for replicaset to select the pods
      project: roboshop
      tier: database
      component: rabbitmq
      environment: dev
  template:
    metadata:
    # these for pod defination
      labels:
        project: roboshop
        tier: database
        component: rabbitmq
        environment: dev
    spec:
      containers:
      - name: rabbitmq
        image: krishna88s/rabbitmq:1.1.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          failureThreshold: 4
          periodSeconds: 10 
        envFrom:
        - configMapRef:
            name: rabbitmq-configmap


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
      project: roboshop
      tier: database
      component: rabbitmq
      environment: dev

  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672

